### ISSUE TITLE
"Projects" capability. 

### ISSUE THREAD

**Issue by Grendel61** [formulahendry/vscode-node-red#1]
I have the Node Red "Projects" editor theme running. Settings.js = 
`    editorTheme: {
        projects: {
            enabled: true`

I brought up the vscode-node-red, and it is defaulting to how Node-Red works without projects. It seems like it overrode the settings.js. Otherwise everything is loaded properly. Any thoughts on a hack? 
https://nodered.org/docs/user-guide/projects/

**Comment by Grendel61** [comment]
Any thoughts on a work around.?

**Comment by BartNetJS** [comment]
I have a similar issue. I've opened vs-vode in a node-red folder, and the node-red extension shows my last flow instead of the one in the folder with a settings.js file

**Comment by formulahendry** [comment]
Hi @Grendel61 @BartNetJS , thanks for your feedback! Since we embed Node-RED in VS Code as a Node.js application, it seems not respect settings.js directly. I have release a new version to support config those settings as settings.js file. You could go to `File`->`Preferences`->`Settings` to config like below:
```json
"vscode-node-red.settings.js": {
        "editorTheme": {
            "projects": {
                "enabled": true
            }
        }
    }
```

**Comment by Grendel61** [comment]
Thanks for the change.
